### ISSUE TITLE
Hello, I have some problems  about your complementary code for "GroundR"

### ISSUE THREAD

**Issue by junleiz** [brunoprela/multiple_blockchain_swarm_robotics#2]
Hi,
    I am sorry to bother you. I have some problems about your complementary code named "GroundR".  But I can not find the way to contact with you, I leave the message in this project.^-^
    `
   if m > 1

            curxmin = 0;

            curxmax = 0;

            curymin = 0;

            curymax = 0;

            for j = 1:m

                curLabel = Ann.labels(boxindex{1}(j, 1));

                if isempty(curLabel.scene) && isempty(curLabel.nobox)

                    curbox = curLabel.boxes;

                    %nobox = curLabel.nobox;

                    %[a, b] = size(box)

                    %disp(isempty(nobox));

                    curxmin = min(curxmin, curbox(1));

                    curymin = min(curymin, curbox(2));

                    curxmax = max(curxmax, curbox(3));

                    curymax = max(curymax, curbox(4));` 
I want to know if there is any problem in the last four line. For example, if my groundtruth if [3, 100, 3, 100], it will return cur[0, 0, 3, 100]. And when you calculate the "iou" you use the result about [0, 0, 3, 100] with the proposals. I think you should use the [3, 100, 3, 100] instead of the [0, 0, 3, 100]. I want to know if I misunderstand it?

**Comment by brunoprela** [comment]
Hello, thank you for taking interest in that repo. I know it is quite badly documented on our end and theres a lot of confusing unused code. I don't know if I fully understand what your question is but I believe you're trying to generate proposal boxes. There is some code in `annotation_generator.py` which is misleading. We did not use selective search ourselves to get the proposal boxes but rather used the fine-tuned visual features found here: [https://github.com/kanchen-usc/QRC-Net/blob/master/feature/README.md](url), despite the fact we have a `get_Iou(b1,b2)` function there (which is never used). I would recommend using those proposals first and then modifying your project to use your own generated proposals afterwards, but whatever floats your boat.

As for help with the last four lines if you'd like to do this generation yourself, you can see the functions in `annotation_generator.py`. I believe you have your max and mins switched up:

```
def get_Iou(b1, b2):
	xmin = np.max(b1[0], b2[0])
	ymin = np.max(b1[1], b2[1])
	xmax = np.min(b1[2], b2[2])
	ymax = np.min(b1[3], b2[3])

	intersection = get_area(xmax - xmin, ymax - ymin)
	union = get_area(b1[2] - b1[0], b1[3] - b1[1]) + get_area(b2[2] - b2[0], b2[3] - b2[1]) - intersection
	return intersection / union

def get_area(w, h):
	return w * h
```

**Comment by brunoprela** [comment]
This issue was moved to brunoprela/GroundeR#1
Feel free to reopen it if needed.
